// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package listen

import (
	"time"
)

type ListenRequest struct {
	SenderID   string      `json:"senderID"`
	SenderName string      `json:"senderName"`
	Room       *ListenRoom `json:"room"`
}

type ListenRoom struct {
	Name       string      `json:"name"`
	Owner      string      `json:"owner"`
	PlaylistID string      `json:"playlistID"`
	Messages   []*Message  `json:"messages"`
	Listeners  []*Listener `json:"listeners"`
}

type Listener struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Message struct {
	ID        string    `json:"id"`
	Text      string    `json:"text"`
	CreatedBy string    `json:"createdBy"`
	CreatedAt time.Time `json:"createdAt"`
}
